### ISSUE TITLE
Implement FSM Driver Logic

### ISSUE THREAD

**Issue by PostMatthew** [PostMatthew/Laptime_Simulation_ME391#29]

**Comment by PostMatthew** [comment]
Implemented Four Block Structure & Driver Logic but simulation seems to be caught in endless loop and isn't producing any results now. @Alexanderallenbrown I just uploaded it to week #5 updates branch. Can you take a look?

**Comment by Alexanderallenbrown** [comment]
@PostMatthew which file is this in? Notebook or all-in-one script?
